### ISSUE TITLE
Missing sensors 

### ISSUE THREAD

**Issue by Hellowlol** [custom-components/sensor.avfallsor#19]
Rest avfall and bio are missing

**Comment by c-stepps** [comment]
any progress with this issue?

**Comment by Hellowlol** [comment]
Nei, jeg har ikke hatt anledning til å se på det. HTML strukturen er endret så det må gjøre på en annen måte

**Comment by c-stepps** [comment]
Metal mangler også nå.

**Comment by hpfuruborg** [comment]
Håper på en oppdatering av dette snart - kona savner det :)

**Comment by Gizmopower1** [comment]
Ingen sensorer virker nå.. :(

**Comment by stalegjelsten** [comment]
For meg var det bare restavfall og matavfall som ikke fungerte. Jeg har gjort en kjapp fiks  for min egen del, se PR #20. 

Den eneste fila som er endret er `utils.py`, så hvis noen av dere ønsker å teste ut fixen før den eventuelt blir merget her, så kan dere erstatte `homassistant-mappe/custom_components/avfallsor/utils.py` med `utils.py` i min Pull Request.
