### ISSUE TITLE
Avfallsør remade the site

### ISSUE THREAD

**Issue by yurgh** [custom-components/sensor.avfallsor#6]
Collecting data doesn't work anymore due to the webpage changing.
https://avfallsor.no/

**Comment by Hellowlol** [comment]
Thanks. Lets hope they added a api..

**Comment by Hellowlol** [comment]
Can you update to the latest version and see if this solved your issue?

**Comment by Hellowlol** [comment]
Closing this issue as v0.0.2 has been confirmed to be working.

**Comment by yurgh** [comment]
Working great (as you already have confirmed) - thanks a lot 👍
